import w1 from "../img/w1.gif";
import w2 from "../img/w6.gif";
import w3 from "../img/w3.gif";
import w4 from "../img/w4.gif";
import w5 from "../img/m4a1.gif";
import w6 from "../img/w2.gif";

export const weapons = [
  {
    name: "AK7U",
    image: w1,
    id: "1",
    type: "Assault-Rifle",
    country: "Russia",
    damage: 60,
    accuracy: 70,
    range: 50,
    fireRate: 40,
    mobility: 90,
    control: 60,
  },
  {
    name: "Colt M-4 ",
    image: w2,
    id: "2",
    type: "Assault-Rifle",
    country: "USA",
    damage: 60,
    accuracy: 70,
    range: 50,
    fireRate: 40,
    mobility: 60,
    control: 60,
  },
  {
    name: "Nikonov AN-94",
    image: w3,
    id: "3",
    type: "Assault-Rifle",
    country: "Russia",
    damage: 60,
    accuracy: 30,
    range: 50,
    fireRate: 20,
    mobility: 40,
    control: 70,
  },
  {
    name: "AK7U",
    image: w4,
    id: "1",
    type: "Submachine Gun",
    country: "Russia",
    damage: 10,
    accuracy: 10,
    range: 40,
    fireRate: 70,
    mobility: 60,
    control: 30,
  },
  {
    name: "AK7U",
    image: w5,
    id: "1",
    type: "Assault-Rifle",
    country: "Russia",
    damage: 90,
    accuracy: 80,
    range: 50,
    fireRate: 20,
    mobility: 10,
    control: 50,
  },
  {
    name: "AK7U",
    image: w6,
    id: "1",
    type: "Assault-Rifle",
    country: "Russia",
    damage: 2,
    accuracy: 8,
    range: 9,
    fireRate: 6,
    mobility: 1,
    control: 6.5,
  },
];
