import w1 from "../img/w1.gif";
import w2 from "../img/w6.gif";
import w3 from "../img/w3.gif";
import w4 from "../img/w4.gif";
import w5 from "../img/m4a1.gif";
import w6 from "../img/w2.gif";

export const weapons = [
  {
    name: "AK7U",
    image: w1,
    id: "1",
    type: "Submachine Gun",
    country: "Russia",
    damage: " * * * * * * / / / /",
    accuracy: " * * * * * / / / / ",
    range: " * * * * / / / / / /",
    fireRate: " * * * * * * * * * /",
    mobility: " * * * * * * * * * *",
    control: " * * * * * * * / / /",
  },
  {
    name: "Colt M-4 ",
    image: w2,
    id: "2",
    type: "Submachine Gun",
    country: "USA",
    damage: " * * * * * * * * * /",
    accuracy: " * * * * * / / / / ",
    range: " * * * * * * * * * /",
    fireRate: " * * * * * * / / / /",
    mobility: " * * * * * * / / / /",
    control: " * * * * * * * * / /",
  },
  {
    name: "Nikonov AN-94",
    image: w3,
    id: "3",
    type: "Submachine Gun",
    country: "Russia",
    damage: " * * * * * * * * * *",
    accuracy: " * * * * * * * / / ",
    range: " * * * * * * * * * /",
    fireRate: " * * * * * * * * / /",
    mobility: " * * * * * / / / / /",
    control: " * * * * * * / / / /",
  },
  {
    name: "AK7U",
    image: w4,
    id: "1",
    type: "Submachine Gun",
    country: "Russia",
    damage: " * * * * * * / / / /",
    accuracy: " * * * * * / / / / ",
    range: " * * * * / / / / / /",
    fireRate: " * * * * * * * * * /",
    mobility: " * * * * * * * * * *",
    control: " * * * * * * * / / /",
  },
  {
    name: "AK7U",
    image: w5,
    id: "1",
    type: "Submachine Gun",
    country: "Russia",
    damage: " * * * * * * / / / /",
    accuracy: " * * * * * / / / / ",
    range: " * * * * / / / / / /",
    fireRate: " * * * * * * * * * /",
    mobility: " * * * * * * * * * *",
    control: " * * * * * * * / / /",
  },
  {
    name: "AK7U",
    image: w6,
    id: "1",
    type: "Submachine Gun",
    country: "Russia",
    damage: " * * * * * * / / / /",
    accuracy: " * * * * * / / / / ",
    range: " * * * * / / / / / /",
    fireRate: " * * * * * * * * * /",
    mobility: " * * * * * * * * * *",
    control: " * * * * * * * / / /",
  },
];
